/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as CanalNetworkRouteImport } from './routes/canal.$network'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const CanalNetworkRoute = CanalNetworkRouteImport.update({
  id: '/canal/$network',
  path: '/canal/$network',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/panel': typeof PanelRoute
  '/reglas': typeof ReglasRoute
  '/canal/$network': typeof CanalNetworkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/panel': typeof PanelRoute
  '/reglas': typeof ReglasRoute
  '/canal/$network': typeof CanalNetworkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/panel': typeof PanelRoute
  '/reglas': typeof ReglasRoute
  '/canal/$network': typeof CanalNetworkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/historial' | '/panel' | '/reglas' | '/canal/$network'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historial' | '/panel' | '/reglas' | '/canal/$network'
  id: '__root__' | '/' | '/historial' | '/panel' | '/reglas' | '/canal/$network'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistorialRoute: typeof HistorialRoute
  PanelRoute: typeof PanelRoute
  ReglasRoute: typeof ReglasRoute
  CanalNetworkRoute: typeof CanalNetworkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canal/$network': {
      id: '/canal/$network'
      path: '/canal/$network'
      fullPath: '/canal/$network'
      preLoaderRoute: typeof CanalNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistorialRoute: HistorialRoute,
  PanelRoute: PanelRoute,
  ReglasRoute: ReglasRoute,
  CanalNetworkRoute: CanalNetworkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
